tablet_query = """title NOT ILIKE '%Suporte%'
 AND title NOT ILIKE '%Pelicula%'
 AND title NOT ILIKE '%Capa%'
 AND title NOT ILIKE '%Capinha%'
 AND title NOT ILIKE '%Cordão%'
 AND title NOT ILIKE '%Caneta%'
 AND title NOT ILIKE '%Protetores%'
 AND title NOT ILIKE '%Mesa digitalizadora%'
 AND title NOT ILIKE '%Teclado%'
 AND title NOT ILIKE '%mouse%'
 AND title NOT ILIKE '%bloco%'
 AND title NOT ILIKE '%Kindle%'
 AND title NOT ILIKE '%Protetor%'
 AND title NOT ILIKE '%Display%'
 AND title NOT ILIKE '%smartphone%'
 AND title NOT ILIKE '%adaptador%'
 AND title NOT ILIKE '%mochila%'
AND title NOT ILIKE '%Película%'
AND title NOT ILIKE '%Luvas%'
AND title NOT ILIKE '%GoodFixer%'
AND title NOT ILIKE '%Carregador%'
AND title NOT ILIKE '%Bolsa%'
AND title NOT ILIKE '%Case%'
AND title NOT ILIKE '%ADEGA PAD16E BIVOLT PHILCO%'
AND title NOT ILIKE '%Apple Pencil%'
AND title NOT ILIKE '%Keyboard%'
AND title NOT ILIKE '%Mouse%'
AND title NOT ILIKE '%Folio%'
AND title NOT ILIKE '%Microfone%'
AND title NOT ILIKE '%eletronico%'
AND title NOT ILIKE '%cápsulas%'
AND title NOT ILIKE '%Pen%'
AND title NOT ILIKE '%Pencil%'
AND title NOT ILIKE '%Songs From The Hill / Tablet%'
AND title NOT ILIKE '%Multivitamínico%'
AND title NOT ILIKE '%Notebookz%' """