known_brands: list = [
    "ACER", "ASUS", "SAMSUNG", "Dell", "Positivo", "Lenovo", "VAIO",
    "HP", "Apple", "Multilaser", "Anvazise", "ASHATA", "Santino", "MSI",
    "Marca Fácil", "Microsoft", "AWOW", "Gateway", "Compaq", "DAUERHAFT",
    "SGIN", "Luqeeg", "Kiboule", "LG", "Panasonic", "Focket", "Toughbook",
    "LTI", "GIGABYTE", "Octoo", "Chip7 Informática", "GLOGLOW", "GOLDENTEC",
    "KUU", "HEEPDD", "Adamantiun", "Naroote", "Jectse", "Heayzoki", "Galaxy",
    "Motorola", "Xiaomi", "Nokia", "Poco", "realme", "Infinix", "Blu",
    "Gshield", "Geonav", "Redmi", "Gorila Shield", "intelbras", "TCL",
    "Tecno", "Vbestlife", "MaiJin", "SZAMBIT", "Otterbox", "Sony",
    "HAIZ", "HUAWEI", "HAYLOU", "Amazfit", "Ticwatch", "Legado Engenharia",
    "Microwear", "Lefal Cold", "MPOWER", "Kaymcixs", "Garmin", "123Smart",
    "Technos", "IWO", "Polar", "Mormaii", "xsmart",
    "EIGIIS", "Beyamis", "Hrich", "ANCOOL", "Dpofirs", "C7 company",
    "ShieldForce", "FIT IT", "Blackview", "KALINCO", "Danet", "LDFAS",
    "VINGVO", "MIJOBS", "KADES", "Naroote", "Gusfeliz",
    "Fossil", "Withings", "Suunto", "Mobvoi", "Amazfit", "Garmin", "Fitbit",
    "Huawei", "Apple", "Samsung", "TicWatch", "Polar", "Tag Heuer", "Casio",
    "Amazfit", "Garmin", "Suunto", "Huawei", "Fitbit", "Amazfit", "Withings",
    "Fossil", "Huawei", "Michael Kors", "Misfit", "TomTom", "Jawbone", "Zepp","Philco",
    "Britânia", "Roku", "Dolby", "Philips", "Semp"
]